/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import ManejosDeDatoExternos.*;
import java.awt.Color;
import java.awt.*;
import java.util.*;
import java.awt.event.*;

/**
 *
 * @author jean torres
 */
public class PetecionDeDatos extends javax.swing.JFrame {

    private String divisaOriginal, divisaCambio;
    private double valorDivisaOriginal, valorDivisaCambio;
    private PaisesMasSimbolos simboloDivisa = new PaisesMasSimbolos();
    private PeticionDatos valorDatos = new PeticionDatos();
    private final Herramientas numeroRecortado = new Herramientas();

    /**
     * Creates new form PetecionDeDatos
     */
    public PetecionDeDatos() {
        initComponents();
        this.setSize(665, 398);
        this.setLocationRelativeTo(this);

        cargarNombresPaises();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                divisaCambio = (String) jcMonedaCambio.getSelectedItem();

                String simbolo = simboloDivisa.getSimbolo(divisaCambio);

                valorDivisaCambio = valorDatos.getValor(simbolo);
                calcularCambioDeArribaAbajo();
                mensajes();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlValorInformativo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlPaisInformativo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        monedaOriginal = new javax.swing.JTextField();
        jcMonedaOriginal = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        monedaCambio = new javax.swing.JTextField();
        jcMonedaCambio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de divisas");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlValorInformativo.setDisplayedMnemonic('0');
        jlValorInformativo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlValorInformativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlValorInformativo.setText("0.00025 Dólar estadounidense");
        jlValorInformativo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jlValorInformativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 400, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conversor de divisas");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 60));

        jlPaisInformativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPaisInformativo.setText("1 Peso colombiano Es igual a");
        jlPaisInformativo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jlPaisInformativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 400, 40));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 190, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monedaOriginal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        monedaOriginal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaOriginal.setText("1");
        monedaOriginal.setBorder(null);
        monedaOriginal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        monedaOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monedaOriginalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monedaOriginalKeyTyped(evt);
            }
        });
        jPanel2.add(monedaOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 55));

        jcMonedaOriginal.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jcMonedaOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcMonedaOriginal.setBorder(null);
        jcMonedaOriginal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcMonedaOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMonedaOriginalActionPerformed(evt);
            }
        });
        jPanel2.add(jcMonedaOriginal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 55));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 410, 55));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monedaCambio.setEditable(false);
        monedaCambio.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        monedaCambio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        monedaCambio.setText("0");
        monedaCambio.setBorder(null);
        monedaCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(monedaCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 205, 55));

        jcMonedaCambio.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jcMonedaCambio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcMonedaCambio.setBorder(null);
        jcMonedaCambio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcMonedaCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMonedaCambioActionPerformed(evt);
            }
        });
        jPanel3.add(jcMonedaCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 210, 55));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 410, 55));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcMonedaOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMonedaOriginalActionPerformed
        // TODO add your handling code here:
        try {
            divisaOriginal = (String) jcMonedaOriginal.getSelectedItem();

            String simbolo = simboloDivisa.getSimbolo(divisaOriginal);

            valorDivisaOriginal = valorDatos.getValorPrincipal(simbolo);

            calcularCambioDeArribaAbajo();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jcMonedaOriginalActionPerformed

    private void jcMonedaCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMonedaCambioActionPerformed
        // TODO add your handling code here:
        try {
            divisaCambio = (String) jcMonedaCambio.getSelectedItem();

            String simbolo = simboloDivisa.getSimbolo(divisaCambio);

            valorDivisaCambio = valorDatos.getValor(simbolo);

            calcularCambioDeArribaAbajo();

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jcMonedaCambioActionPerformed

    private void monedaOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monedaOriginalKeyTyped
        // TODO add your handling code here:
        if (monedaOriginal.getText().length() < 12) {
            char c = evt.getKeyChar();
            if (Character.isDigit(c)) {
                calcularCambioDeArribaAbajo();
            } else {
                Toolkit.getDefaultToolkit();
                evt.consume();
            }
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit();
        }
    }//GEN-LAST:event_monedaOriginalKeyTyped

    private void monedaOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monedaOriginalKeyReleased
        // TODO add your handling code here:
        calcularCambioDeArribaAbajo();
    }//GEN-LAST:event_monedaOriginalKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetecionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetecionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetecionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetecionDeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetecionDeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcMonedaCambio;
    private javax.swing.JComboBox<String> jcMonedaOriginal;
    private javax.swing.JLabel jlPaisInformativo;
    private javax.swing.JLabel jlValorInformativo;
    private javax.swing.JTextField monedaCambio;
    private javax.swing.JTextField monedaOriginal;
    // End of variables declaration//GEN-END:variables

    private void cargarNombresPaises() {
        jcMonedaOriginal.removeAllItems();
        jcMonedaCambio.removeAllItems();

        PaisesMasSimbolos paises = new PaisesMasSimbolos();

        TreeSet<String> nombresPaises = paises.getPaises();
        for (String pais : nombresPaises) {
            jcMonedaCambio.addItem(pais);
            jcMonedaOriginal.addItem(pais);
        }
        jcMonedaOriginal.setSelectedIndex(153);
        jcMonedaCambio.setSelectedIndex(33);
    }

    private void calcularCambioDeArribaAbajo() {
        if (!monedaOriginal.getText().isEmpty()) {
            monedaCambio.setText(String.valueOf(valorDivisaCambio * Double.parseDouble(monedaOriginal.getText())));
            mensajes();
        }
    }

    private void mensajes() {
        if (!monedaOriginal.getText().isEmpty() || !monedaCambio.getText().isEmpty()) {
            jlPaisInformativo.setText("1 " + jcMonedaOriginal.getSelectedItem().toString() + " es igual a");
            String miniNumero = numeroRecortado.recortarNumero(valorDivisaCambio / valorDivisaOriginal).toString();
            jlValorInformativo.setText(miniNumero + " " + jcMonedaCambio.getSelectedItem().toString());
            System.out.println(miniNumero + jlValorInformativo.getText());
        }
    }

    private void rediseño() {

        jcMonedaOriginal.setBackground(new Color(0, 0, 0, 0));
        jcMonedaCambio.setBackground(new Color(0, 0, 0, 0));
        monedaCambio.setBackground(new Color(0, 0, 0, 0));
        monedaOriginal.setBackground(new Color(0, 0, 0, 0));
    }
}
